# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OnTheWayMain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for OnTheWayMain
  pod 'Mapbox-iOS-SDK', '~> 3.5'
  pod 'FBSDKLoginKit'
  pod 'SwiftLint'
  #  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Alamofire', '~> 4.4'
  pod 'PageMenu'
  pod 'RealmSwift'
  pod 'ObjectMapper'
end


