# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnTheWayMain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  # Pods for OnTheWayMain
  pod 'FBSDKLoginKit'
  pod 'Alamofire'
  pod 'ObjectMapper'
end
